### ISSUE TITLE
Improvement for usercallback.notify

### ISSUE THREAD

**Issue by ghost** [bit-team/user-callback#2]
I have two suggestions for the usercallback.notify:

**1. Onscreen display**

In same cases, `notify-send` does not work, but `zenity` does.

Hence, I would suggest adding

        zenity --info --text "BackInTime backup for profile ${iBackInTimeProfileID} (${szBackInTimeProfileName}) completed" &

to 2) (backup finished) and

        zenity --error --title="BackInTime" --text="BackInTime backup for profile ${iBackInTimeProfileID} (${szBackInTimeProfileName}) failed on $(date +%Y-%m-%d_%H-%M-%S) with error $szBackInTimeErrorMessagee" &

to 4) (error).

~~For 1) and 3), zenity might no be such a good idea, because at least for me the dialogue seems to block the continuation of the usercallback script.~~

To prevent `zenity` from blocking the script flow just add `&` after the command.

**2. Mail**

In my case, the following line did not work:

     mail --subject="$szBackInTimeErrorMessage$(date +%Y-%m-%d)" --to "$szBackInTimeEMailAddress"<~/.local/share/backintime/takesnapshot_.log

It was required to be replace by:

        cat ~/.local/share/backintime/takesnapshot_.log | mail -s "BackInTime backup for profile ${iBackInTimeProfileID} (${szBackInTimeProfileName}) failed on $(date +%Y-%m-%d_%H-%M-%S) with error $szBackInTimeErrorMessage" $szBackInTimeEMailAddress

(There are some minor changes to the text included as well.)

**Comment by Germar** [comment]
Thanks for the improvements. Could you please create a pull-request? I'll merge it...
